- README.md
Reason:
AtCoderHub has already existed
> Rename repo name (#118)

- media.md
- monthly_changelog/2020_11.md
> :boom: Replace new URL (#3802)

- media.md
> :sparkles: Add article (#4078)

- libraries.md
https://github.com/key-moon/ac-library-cs は https://github.com/kzrnm/ac-library-csharp へ引き継がれているので、リダイレクトするようになっています。
事実上、重複リンクになってしまっているので統合した方が良いかと思います。
https://github.com/kzrnm/ac-library-csharp/issues/72
> ac-library-cs is deprecated

- docs/articles/implementation.md
> :sparkles: Add article (#4500)

- docs/libraries/library_checker.md
> :sparkles: Add article (#5227)

- docs/libraries/library_checker.md
> :sparkles: Add article (#5221)

- docs/articles/implementation.md
> :sparkles: Add article (#5264)

- docs/articles/implementation.md
> :sparkles: Add article (#5993)

- docs/archived/outdated_information.md
- docs/web_app/support_tools.md
> :boom: Move web app to archives (#6516)

- docs/articles/how_to_practice.md
- docs/changelog/2022_03.md
> :books: Update url (#6518)

- docs/articles/math.md
> :sparkles: Add article (#6521)

- docs/articles/heuristic.md
> :sparkles: Add slide (#6923)

- docs/articles/math.md
> :sparkles: Add article (#6911)

- docs/articles/view_scores.md
> :sparkles: Add article (#6922)

- docs/articles/view_scores.md
> :sparkles: Add article (#6983)

- docs/articles/introduction.md
- docs/for_beginners/question1.md
> ✨ Add ADT (#7027)

- docs/sns/index.md
Discord サーバー kyoprustecean をご紹介いただきありがとうございます。
設立当初、セキュリティ上の懸念で無期限リンクを発行しておらず、AtCoder Clans にも期限切れのリンクが掲載されており、みなさまにご不便をおかけしすぎているため、このたび発行しようと思いました。
お手数ですがよろしくお願いいたします。
> kyoprustecean の招待リンクを無期限にする

- docs/articles/heuristic.md
> ✨ Add article (#7670)

- docs/archived/outdated_information.md
- docs/related_contest_sites/topcoder.md
コンテストへの参加方法を紹介した記事をarchviesへの移動させました。
新規の新しいコンテストサイトが開設されたら、参加方法が変わるためと思われるためです。
> :boom: Move articles to archives (#8529)

- docs/articles/heuristic.md
> ✨ Add article (#9504)

- docs/changelog/latest.md
- docs/index.md
> 🔊 Update CHANGELOG (#9578)

- docs/articles/heuristic.md
> ✨ Add article (#9591)
