docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5422)

docs/blogs/heuristic/cpp.md
=> :sparkles: Add and update blogs (#5316)

docs/articles/heuristic.md
=> :sparkles: Add article (#5353)

docs/blogs/algorithm/python.md
=> :sparkles: Update blogs (#5393)

docs/articles/how_to_practice.md, docs/changelog/2022_03.md
=> :books: Ignore links (#5433)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5428)

docs/milestones/green.md
=> :sparkles: Add article (#5440)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5441)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5444)

docs/milestones/cyan.md
=> :sparkles: Add article (#5449)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5451)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5456)

docs/articles/heuristic.md
=> :sparkles: Add article (#4430)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5463)

docs/articles/development_env.md
=> :sparkles: Add article (#5466)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5465)

docs/milestones/green.md
=> :sparkles: Add article (#5470)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5473)

docs/milestones/green.md
=> :sparkles: Add article (#5477)

docs/milestones/brown.md
=> :sparkles: Add article (#5471)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5480)

docs/articles/development_env.md
=> :sparkles: Add repo (#5469)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5482)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5486)

docs/articles/heuristic.md
=> :sparkles: Add article (#5488)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5491)

docs/changelog/template.md
=> :docs: Update template for changelog (#5494)

docs/archived/broken_links.md, docs/milestones/brown.md, monthly_changelog/2021_06.md
=> :boom: Remove dead links (#5496)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5497)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5505)

docs/milestones/brown.md
=> :sparkles: Add article (#5508)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5509)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5513)

docs/sns/index.md
=> :sparkles: Add discord server (#5489)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5518)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5525)

docs/articles/algorithm.md
=> :sparkles: Add article (#5517)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5528)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5531)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5537)

docs/milestones/brown.md
=> :sparkles: Add article (#5542)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5541)

docs/articles/heuristic.md, docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5549)

docs/milestones/green.md
=> :sparkles: Add article (#5545)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5553)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5557)

docs/blogs/heuristic/cpp.md, docs/blogs/heuristic/python.md, docs/blogs/heuristic/rust.md
=> :sparkles: Add and update blogs (#5317)

docs/sns/index.md
=> :sparkles: Add discord server (#5560)

docs/articles/heuristic.md
=> :sparkles: Add article (#5556)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5561)

docs/milestones/green.md
=> :sparkles: Add article (#5571)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5576)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5580)

docs/articles/how_to_practice.md
=> :sparkles: Add article (#5583)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5585)

docs/milestones/blue.md
=> :sparkles: Add article (#5536)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5588)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5597)

docs/articles/heuristic.md
=> :sparkles: Add slide (#5503)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5603)

docs/blogs/algorithm/cpp.md
=> :sparkles: Add blog (#5564)

docs/milestones/yellow.md
=> :sparkles: Add article (#5608)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5610)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5612)

docs/related_contest_sites/joi_ioi.md
=> :loud_sound: Update CHANGELOG (#5617)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5622)

docs/user_scripts/submit_codes.md
=> :sparkles: Add script (#5459)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5625)

docs/libraries/articles.md
=> :sparkles: Add article (#5630)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5629)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5635)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5639)

docs/articles/heuristic.md
=> :sparkles: Add article (#5643)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5646)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5654)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5658)

docs/blogs/heuristic/cpp.md, docs/blogs/heuristic/python.md, docs/blogs/heuristic/rust.md
=> :sparkles: Add and update blogs (#5563)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5662)

docs/milestones/blue.md
=> :sparkles: Add article (#5679)

docs/archived/broken_links.md, docs/changelog/2023_01.md, docs/milestones/brown.md
=> :boom: Move dead links to archives (#5671)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5682)

docs/for_beginners/question0.md, docs/youtube/video.md
=> :sparkles: Add video (#5666)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5688)

docs/youtube/channel.md
=> :sparkles: Add channel (#5647)

docs/milestones/blue.md, docs/milestones/brown.md, docs/milestones/cyan.md, docs/milestones/green.md, docs/milestones/orange.md, docs/milestones/red.md, docs/milestones/retirement.md, docs/milestones/yellow.md
=> :books: Fix order of articles (#5695)

docs/milestones/brown.md
=> :sparkles: Add article (#3228)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5694)

docs/user_scripts/participate_in_contests.md
=> :sparkles: Add script (#5702)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5707)

docs/milestones/cyan.md
=> :sparkles: Add article (#5701)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5713)

docs/articles/introduction.md
=> :sparkles: Add article (#5718)

docs/milestones/green.md
=> :sparkles: Add article (#5711)

docs/articles/jobs.md
=> :sparkles: Add article (#5722)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5716)

docs/articles/implementation.md
=> :sparkles: Add article (#5728)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5730)

docs/index.md
=> :books: Update descriptions (#5708)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5737)

docs/index.md
=> :books: Update descriptions (#5744)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5740)

docs/articles/implementation.md
=> :sparkles: Add article (#5749)

docs/articles/implementation.md, docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5752)

docs/articles/algorithm.md
=> :sparkles: Add article (#5756)

docs/articles/algorithm.md
=> :sparkles: Add article (#5733)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5759)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5762)

docs/articles/algorithm.md
=> :sparkles: Add article (#5710)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5765)

docs/milestones/blue.md
=> :sparkles: Add article (#5770)

docs/articles/implementation.md
=> :sparkles: Add article (#5769)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5771)

mlc_config.json
=> 💥 Ignore link (#5775)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5779)

docs/articles/algorithm.md
=> :sparkles: Add article (#5584)

docs/articles/heuristic.md
=> :sparkles: Add articles (#5784)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5781)

docs/milestones/green.md
=> :sparkles: Add articles (#5791)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5792)

docs/user_scripts/solve_problems.md
=> :sparkles: Add script (#5589)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5795)

mlc_config.json
=> 💥 Ignore link (#5800)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5803)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5807)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5815)

docs/articles/algorithm.md
=> :sparkles: Add article (#5811)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5818)

docs/for_beginners/question3.md
=> :sparkles: Add article (#5824)

docs/articles/implementation.md
=> :sparkles: Add article (#5820)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5826)

docs/blogs/algorithm/python.md
=> :sparkles: Add blog (#5829)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5830)

docs/milestones/cyan.md
=> :sparkles: Add article (#5835)

docs/milestones/brown.md
=> :sparkles: Add article (#5834)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5838)

docs/milestones/yellow.md
=> :sparkles: Add article (#5842)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5844)

docs/changelog/latest.md, docs/user_scripts/submit_codes.md, docs/web_app/solve_problems.md
=> :loud_sound: Update CHANGELOG (#5847)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#5686)

docs/milestones/blue.md
=> :sparkles: Add article (#5851)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5850)

docs/related_contest_sites/security.md
=> :sparkles: Add advent calendar (#5675)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5856)

docs/articles/heuristic.md
=> :sparkles: Add article (#5864)

docs/articles/user_editorials.md, docs/changelog/2022_04.md
=> :books: Update site url (#5615)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5865)

docs/articles/how_to_approach_difficult_problems.md
=> :sparkles: Add article (#5226)

docs/web_app/solve_problems.md
=> :sparkles: Add article (#5677)

docs/milestones/cyan.md
=> :sparkles: Add article (#5871)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5872)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5877)

docs/articles/introduction.md
=> :sparkles: Add article (#5881)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5884)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5887)

mlc_config.json
=> 💥 Ignore links (#5892)

docs/articles/heuristic.md
=> :sparkles: Add article (#5890)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5891)

mlc_config.json
=> 💥 Ignore links (#5899)

docs/articles/how_to_approach_difficult_problems.md
=> ✨ Add link of articles (#5897)

docs/articles/heuristic.md, docs/changelog/2022_12.md
=> :books: Ignore links (#5911)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5910)

docs/milestones/brown.md
=> :sparkles: Add article (#5916)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5917)

docs/cli/tools_for_writers.md
=> :sparkles: Add article (#5915)

docs/milestones/cyan.md
=> :sparkles: Add article (#5922)

docs/milestones/yellow.md
=> :sparkles: Add article (#5924)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#5927)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5932)

docs/articles/algorithm.md
=> :sparkles: Add article (#5928)

docs/milestones/green.md
=> :sparkles: Add article (#5925)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5940)

docs/milestones/blue.md
=> :sparkles: Add article (#5933)

docs/milestones/green.md
=> :sparkles: Add article (#5939)

docs/milestones/cyan.md
=> :sparkles: Add article (#5944)

docs/libraries/python.md
=> :sparkles: Add Python lib (#5914)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5949)

docs/milestones/blue.md
=> :sparkles: Add article (#5962)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5964)

docs/milestones/retirement.md
=> :books: Update url (#5967)

docs/milestones/cyan.md
=> :sparkles: Add article (#5966)

monthly_changelog/2021_08.md
=> :books: Update url (#5973)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#59659)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5980)

.devcontainer/devcontainer.json, compose.yaml, requirements.txt
=> :wrench: Update settings for container (#5950)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#5979)

docs/milestones/blue.md
=> :sparkles: Add article (#5982)

docs/articles/heuristic.md
=> :sparkles: Add article (#5961)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#5992)

docs/articles/implementation.md
=> :sparkles: Add article (#5995)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6003)

docs/articles/development_env.md
=> :sparkles: Add article (#6009)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6010)

docs/milestones/cyan.md
=> :sparkles: Add article (#6018)

docs/milestones/brown.md
=> :sparkles: Add article (#6025)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6020)

docs/archived/no_longer_available.md, docs/user_scripts/view_scores.md
=> :boom: Move script to archives (#6035)

docs/web_app/solve_problems.md
=> :sparkles: Add support tool (#6021)

docs/web_app/solve_problems.md
=> :sparkles: Add article (#6022)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6023)

docs/milestones/blue.md
=> :sparkles: Add article (#6028)

docs/milestones/cyan.md
=> :sparkles: Add article (#6030)

docs/milestones/green.md
=> :sparkles: Add article (#6031)

docs/milestones/brown.md
=> :sparkles: Add article (#6033)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6053)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6056)

docs/user_scripts/participate_in_contests.md
=> :sparkles: Add script (#6064)

docs/milestones/orange.md
=> :sparkles: Add article (#6060)

docs/blogs/algorithm/python.md
=> :sparkles: Add blog (#6070)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6068)

docs/milestones/brown.md
=> :sparkles: Add article (#6074)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6077)

docs/articles/algorithm.md
=> :sparkles: Add article (#6043)

docs/bot/index.md, docs/web_app/solve_problems.md
=> :sparkles: Add bot (#6017)

docs/bot/index.md
=> :sparkles: Add bot (#4532)

docs/bot/index.md
=> :sparkles: Add bot (#4437)

docs/bot/index.md
=> :sparkles: Add discord channel (#6091)

docs/archived/no_longer_available.md, docs/bot/index.md
=> :boom: Move bot to archives (#6087)

docs/archived/outdated_information.md, docs/web_app/statistics.md
=> :boom: Move web app to archives (#6094)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6084)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6098)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6103)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6108)

docs/articles/algorithm.md, docs/changelog/latest.md
=> :books:  Fix URL (#6112)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6114)

docs/libraries/cpp.md
=> :sparkles: Add C++ lib (#6117)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6122)

docs/articles/algorithm.md
=> :sparkles: Add article (#6125)

docs/articles/algorithm.md
=> :sparkles: Add article (#6120)

docs/books/index.md
=> :book: Categorize books (#6106)

docs/articles/implementation.md
=> :sparkles: Add article (#6082)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6124)

docs/youtube/channel.md
=> :sparkles: Add channel (#6131)

docs/milestones/blue.md
=> :sparkles: Add article (#6134)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6133)

docs/milestones/cyan.md
=> :sparkles: Add article (#6146)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6149)

docs/milestones/green.md
=> :sparkles: Add article (#6151)

docs/blogs/heuristic/cpp.md
=> :sparkles: Add blogs (#5566)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6157)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6163)

docs/articles/heuristic.md
=> :sparkles: Add GitHub repo (#6155)

docs/articles/heuristic.md
=> :sparkles: Add article (#6154)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6167)

docs/libraries/rust.md
=> :sparkles: Add lib (#6154)

docs/libraries/csharp.md
=> :sparkles: Update lib (#6170)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6174)

docs/articles/view_scores.md
=> :sparkles: Add article (#6169)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6176)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6182)

docs/articles/implementation.md
=> :sparkles: Add article (#5957)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6190)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6194)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6197)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6202)

mkdocs.yml
=> 🔧 Add was this page helpful? (#4420)

docs/milestones/cyan.md
=> :sparkles: Add article (#6209)

docs/articles/heuristic.md
=> :sparkles: Add article (#6206)

docs/articles/heuristic.md
=> :sparkles: Add article (#6205)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6211)

docs/archived/no_longer_available.md, docs/archived/outdated_information.md, docs/related_contest_sites/math.md
=> :boom: Move web sites to archives (#6220)

docs/related_contest_sites/math.md
=> :sparkles: Add bot (#6219)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6218)

docs/archived/no_longer_available.md, docs/changelog/latest.md, docs/user_scripts/colors.md
=> :boom: Move deleted script to archives (#6225)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6227)

docs/milestones/green.md
=> :sparkles: Add article (#6230)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6231)

docs/user_scripts/jokes.md
=> :books: Add section (#6235)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6237)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6242)

docs/blogs/algorithm/cpp.md
=> :sparkles: Add blog (#6141)

docs/milestones/yellow.md
=> :sparkles: Add article (#6246)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6244)

docs/blogs/heuristic/cpp.md, docs/blogs/heuristic/csharp.md
=> :sparkles: Add and update blogs (#6140)

docs/milestones/cyan.md
=> :sparkles: Add article (#6250)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6252)

docs/articles/implementation.md
=> :sparkles: Add article (#6256)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6258)

docs/libraries/articles.md
=> :sparkles: Add slide (#6249)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6260)

docs/archived/broken_links.md, docs/related_contest_sites/algorithm.md, monthly_changelog/2021_01.md
=> :boom: Move contest site to archives (#6264)

docs/books/index.md
=> :sparkles: Add book (#6027)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6266)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6269)

docs/milestones/cyan.md
=> :sparkles: Add article (#6278)

docs/articles/heuristic.md
=> :sparkles: Add article (#6276)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6274)

docs/blogs/algorithm/python.md
=> :sparkles: Add blog (#6142)

docs/milestones/cyan.md
=> :sparkles: Add article (#6283)

docs/archived/no_longer_available.md, docs/archived/outdated_information.md, docs/youtube/channel.md
=> :boom: Move YouTube to archives (#6288)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6287)

docs/milestones/cyan.md
=> :sparkles: Add article (#6293)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6294)

docs/blogs/algorithm/cpp.md
=> :sparkles: Add blog (#6292)

docs/articles/implementation.md
=> :sparkles: Add article (#6291)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6298)

docs/milestones/brown.md
=> :sparkles: Add article (#6302)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6305)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6309)

docs/articles/implementation.md
=> :sparkles: Add article (#6310)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6311)

docs/for_beginners/question0.md, docs/youtube/channel.md
=> :sparkles: Add video (#6317)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6318)

docs/user_scripts/colors.md
=> :sparkles: Add script (#6323)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6327)

docs/archived/outdated_information.md, docs/bot/index.md
=> :boom: Move bot to archives (#6320)

docs/books/index.md
=> :sparkles: Add book (#6322)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6331)

docs/sns/index.md
=> :sparkles: Add Misskey.io server (#6337)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6338)

docs/archived/no_longer_available.md, docs/archived/outdated_information.md, docs/bot/index.md, docs/for_beginners/question3.md, docs/related_contest_sites/yukicoder.md
=> :boom: Move bots to archives (#6333)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6347)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6344)

docs/archived/outdated_information.md, docs/web_app/support_tools.md
=> :boom: Move web site to archives (#6360)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6363)

docs/archived/outdated_information.md, docs/web_app/participate_in_contests.md
=> :boom: Remove dead links (#6368)

docs/articles/how_to_practice.md
=> :sparkles: Add spread sheet (#6367)

docs/articles/how_to_practice.md
=> :sparkles: Add article (#6192)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6373)

docs/archived/broken_links.md, docs/related_contest_sites/algorithm.md
=> :boom: Revert contest site (#6377)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6380)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6388)

docs/archived/outdated_information.md, docs/web_app/statistics.md
=> :books: Update with latest info (#6393)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6391)

docs/milestones/brown.md
=> :sparkles: Add article (#6400)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6403)

docs/archived/no_longer_available.md, docs/archived/outdated_information.md, docs/user_scripts/colors.md
=> :boom: Move scripts to archives (#6409)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6405)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6416)

docs/articles/heuristic.md
=> :sparkles: Add article (#6407)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6412)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6413)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6426)

docs/books/index.md
=> :sparkles: Add book (#6102)

docs/youtube/channel.md
=> :sparkles: Add channel (#6428)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6429)

docs/milestones/yellow.md
=> :sparkles: Add article (#6434)

docs/archived/outdated_information.md, docs/cli/test_tools.md
=> :boom: Move cli to archives (#6431)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6435)

docs/articles/algorithm.md, docs/changelog/2023_05.md, docs/changelog/latest.md
=> :books: Fix links (#6442)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6441)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6451)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6450)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6457)

docs/milestones/cyan.md
=> :sparkles: Add article (#6461)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6463)

docs/related_contest_sites/joi_ioi.md
=> :sparkles: Add article (#6470)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6473)

docs/milestones/blue.md
=> :sparkles: Add article (#6479)

docs/archived/outdated_information.md, docs/related_contest_sites/joi_ioi.md
=> :boom: Move article to archives (#6484)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6481)

docs/articles/heuristic.md
=> :sparkles: Add article (#6487)

docs/related_contest_sites/web_services.md
=> :sparkles: Add contest site (#6477)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6490)

docs/articles/heuristic.md, docs/articles/how_to_practice.md, docs/contributing/references.md
=> :books: Ignore link check only links falsely detected (#6498)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6497)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6504)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6505)

docs/archived/outdated_information.md, docs/related_contest_sites/security.md
=> :boom: Move web site to archives (#6506)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6507)

docs/articles/how_to_practice.md
=> :sparkles: Add article (#6512)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6513)

docs/milestones/green.md
=> :sparkles: Add article (#6522)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6525)

docs/articles/implementation/multiple_languages.md
=> :sparkles: Add article (#6528)

docs/articles/implementation/cpp.md
=> :sparkles: Add article (#6529)

docs/articles/implementation/general.md
=> :sparkles: Add gist (#6534)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6537)

docs/articles/implementation/others.md
=> :sparkles: Add article (#6535)

docs/articles/implementation/others.md
=> :sparkles: Add article (#6500)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6541)

docs/articles/algorithm.md
=> :sparkles: Add article (#6546)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6549)

docs/archived/no_longer_available.md, docs/changelog/latest.md, docs/youtube/channel.md
=> :boom: Move YouTube channel to archives (#6552)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6553)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6554)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6556)

docs/articles/heuristic.md
=> :sparkles: Add article (#6561)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6565)

docs/articles/math.md
=> :sparkles: Add slide (#6547)

docs/articles/math.md
=> :sparkles: Add article (#5523)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6570)

docs/related_contest_sites/algorithm.md, docs/web_app/solve_problems.md
=> :sparkles: Add constest site (#6573)

docs/articles/heuristic.md
=> :sparkles: Add article (#6574)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6576)

docs/articles/development_env.md
=> :sparkles: Add article (#6562)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6587)

docs/milestones/blue.md
=> :sparkles: Add article (#6591)

docs/milestones/brown.md
=> :sparkles: Add article (#6593)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6597)

docs/milestones/green.md
=> :sparkles: Add article (#6595)

docs/milestones/brown.md
=> :sparkles: Add article (#6600)

docs/blogs/algorithm/cpp.md
=> :sparkles: Add blog (#6599)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6604)

docs/milestones/cyan.md
=> :sparkles: Add article (#6606)

docs/articles/development_env.md
=> :sparkles: Add article (#6592)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6607)

docs/youtube/video.md
=> :sparkles: Add video (#6619)

docs/articles/algorithm.md
=> :sparkles: Add article (#6616)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6620)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6625)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6627)

docs/articles/implementation/others.md
=> :sparkles: Add article (#6633)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6632)

docs/milestones/cyan.md
=> :sparkles: Add article (#6611)

docs/milestones/green.md
=> :sparkles: Add article (#6612)

docs/archived/no_longer_available.md, docs/archived/outdated_information.md, docs/changelog/2022_03.md
=> :boom: Remove script (#6643)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6644)

docs/articles/heuristic.md
=> :sparkles: Add article (#6650)

docs/cli/test_tools.md
=> :sparkles: Add cli (#6653)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6654)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6659)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6663)

docs/blogs/heuristic/cpp.md, docs/blogs/heuristic/python.md
=> :sparkles: Add and update blogs (#6652)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6666)

docs/articles/heuristic.md
=> :sparkles: Add slide (#6649)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6669)

docs/articles/implementation/rust.md
=> :sparkles: Add article (#6651)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6674)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6679)

docs/articles/heuristic.md
=> :sparkles: Add article (#6685)

docs/articles/club_activities.md, docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6688)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6694)

docs/blogs/heuristic/cpp.md
=> :sparkles: Add blog (#6700)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6702)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6706)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6709)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6708)

docs/milestones/blue.md
=> :sparkles: Add article (#6712)

docs/articles/implementation/python.md
=> :sparkles: Add article (#6678)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6717)

docs/milestones/cyan.md
=> :sparkles: Add article (#6719)

docs/articles/how_to_practice.md
=> :sparkles: Add article (#6661)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6720)

docs/articles/algorithm.md
=> :sparkles: Add article (#6618)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6725)

docs/articles/jobs.md
=> :sparkles: Add article (#6730)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6731)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6736)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6746)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6749)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6756)

docs/articles/jobs.md
=> :sparkles: Add article (#6758)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6759)

docs/archived/no_longer_available.md, docs/user_scripts/colors.md
=> :boom: Move script to archives (#6767)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6765)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6771)

docs/archived/no_longer_available.md, docs/changelog/2022_09.md, docs/changelog/2022_10.md, docs/chrome_extensions/improve_ui.md, docs/milestones/brown.md
=> :boom: Move script to archives (#6780)

docs/blogs/algorithm/cpp.md
=> :sparkles: Add blog (#6696)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6786)

docs/articles/club_activities.md
=> :sparkles: Add article (#6784)

docs/articles/club_activities.md
=> :sparkles: Add article (#6785)

docs/archived/broken_links.md, docs/blogs/algorithm/cpp.md
=> :boom: Move blog to archives (#6792)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6791)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6798)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6805)

docs/articles/algorithm.md
=> :sparkles: Add tweet (#6797)

docs/milestones/orange.md
=> :sparkles: Add article (#6799)

docs/milestones/brown.md
=> :sparkles: Add article (#6801)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6808)

docs/sns/index.md
=> :sparkles: Add X account (#6813)

docs/articles/heuristic.md
=> :sparkles: Add article (#6803)

docs/articles/introduction.md
=> :sparkles: Add article (#6800)

docs/blogs/heuristic/cpp.md, docs/blogs/heuristic/java.md, docs/blogs/heuristic/rust.md
=> :sparkles: Add and update blogs (#6739)

docs/blogs/heuristic/cpp.md, docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6814)

docs/related_contest_sites/joi_ioi.md
=> :sparkles: Add article (#6788)

docs/articles/implementation/others.md
=> :sparkles: Add article (#6821)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6824)

docs/articles/heuristic.md
=> :sparkles: Add article (#6822)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6830)

docs/milestones/blue.md
=> :sparkles: Add article (#6820)

docs/milestones/brown.md
=> :sparkles: Add article (#6833)

docs/bot/index.md
=> :sparkles: Add bot (#6834)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6837)

docs/articles/implementation/python.md
=> :sparkles: Add article (#6790)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6840)

docs/articles/algorithm.md
=> :sparkles: Add article (#6848)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6850)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6854)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6859)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6862)

docs/articles/introduction.md
=> :sparkles: Add article (#6856)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6865)

docs/sns/index.md
=> :sparkles: Add discord server (#6858)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6872)

docs/articles/implementation/others.md
=> :sparkles: Add article (#6857)

docs/articles/user_editorials.md
=> :sparkles: Add blog (#6789)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6877)

docs/milestones/green.md
=> :sparkles: Add article (#6882)

docs/milestones/blue.md
=> :sparkles: Add article (#6871)

docs/milestones/cyan.md
=> :sparkles: Add article (#6866)

docs/articles/how_to_practice.md
=> :sparkles: Add article (#6881)

docs/articles/how_to_practice.md
=> :books: Update description (#6887)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6890)

docs/milestones/cyan.md
=> :sparkles: Add article (#6894)

docs/milestones/green.md
=> :sparkles: Add article (#6896)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6901)

docs/youtube/channel.md
=> :sparkles: Add channel (#6895)

docs/archived/outdated_information.md, docs/youtube/channel.md
=> :boom: Move channel to archives (#6906)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6903)

docs/articles/view_scores.md
=> :sparkles: Add tweet (#6909)

docs/milestones/red.md
=> :sparkles: Add article (#6910)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6918)

docs/articles/heuristic.md
=> :sparkles: Add article (#6915)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6928)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6934)

docs/articles/math.md
=> :sparkles: Add book (#6927)

docs/changelog/latest.md
=> :loud_sound: Update CHANGELOG (#6937)

docs/milestones/blue.md
=> :sparkles: Add article (#6933)

docs/milestones/cyan.md
=> :sparkles: Add article (#6925)

docs/articles/math.md
=> :sparkles: Add Wolfram Alpha (#814)

docs/articles/math.md
=> :sparkles: Add article (#6941)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6947)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6949)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6957)

docs/articles/development_env.md
=> :sparkles: Add article (#6953)

docs/archived/outdated_information.md, docs/articles/development_env.md
=> :boom: Move GitHub repo to archives (#6963)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6966)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6970)

docs/articles/algorithm.md
=> :sparkles: Add article (#6976)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6971)

docs/web_app/for_developers.md, mkdocs.yml
=> :sparkles: Add article (#6942)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6979)

docs/milestones/cyan.md
=> :sparkles: Add article (#6991)

docs/blogs/algorithm/cpp.md
=> :sparkles: Add blog (#6921)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6980)

docs/articles/development_env.md
=> :sparkles: Add article (#6997)

docs/changelog/latest.md, docs/index.md
=> :loud_sound: Update CHANGELOG (#6996)

docs/milestones/cyan.md
=> ✨ Add article (#7002)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7006)

docs/archived/no_longer_available.md, docs/libraries/cpp.md
=> :boom: Move library to archives (#7008)

docs/changelog/latest.md
=> 🔊 Update CHANGELOG (#7010)

docs/articles/view_scores.md
=> ✨ Add tweet (#7013)

docs/articles/heuristic.md
=> ✨ Add GitHub repo (#7005)

docs/youtube/channel.md
=> ✨ Add YouTube channel (#7014)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7018)

docs/index.md
=> ✨ Add GitHub sponsor (#7023)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7020)

docs/articles/implementation/others.md
=> ✨ Add article (#7028)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7026)

docs/archived/broken_links.md, docs/blogs/algorithm/rust.md
=> :boom: Move article to archives (#7038)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7031)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7036)

docs/articles/view_scores.md
=> ✨ Add tweet (#7048)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7052)

docs/changelog/latest.md
=> 🔊 Update CHANGELOG (#7056)

docs/archived/broken_links.md, docs/changelog/2022_11.md, docs/milestones/brown.md
=> :boom: Move article to archives (#7060)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7064)

docs/articles/heuristic.md
=> ✨ Add article (#7045)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7066)

docs/archived/outdated_information.md, docs/cli/template_testcase_generator.md
=> :boom: Move Chrome extension to archives (#7070)

docs/changelog/latest.md
=> 🔊 Update CHANGELOG (#7072)

docs/milestones/blue.md
=> ✨ Add article (#7074)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7079)

docs/milestones/yellow.md
=> ✨ Add article (#7077)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7081)

docs/libraries/cpp.md
=> ✨ Add C++ lib (#7082)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7085)

docs/user_scripts/submit_codes.md
=> ✨ Add article (#7075)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7088)

docs/archived/broken_links.md, docs/changelog/latest.md, docs/milestones/cyan.md
=> :boom: Move article to archives (#7091)

docs/changelog/latest.md
=> 🔊 Update CHANGELOG (#7093)

docs/milestones/cyan.md
=> ✨ Add article (#7098)

docs/milestones/blue.md
=> ✨ Add article (#7099)

docs/articles/view_scores.md
=> ✨ Add tweet (#7097)

docs/articles/view_scores.md
=> ✨ Add tweet (#7107)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7108)

docs/changelog/2022_05.md, monthly_changelog/2021_01.md
=> :boom: Remove deprecated links from changelog (#7112)

docs/articles/club_activities.md
=> ✨ Add article (#7105)

docs/articles/club_activities.md
=> ✨ Add article (#7106)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7113)

docs/articles/heuristic.md
=> ✨ Add article (#7096)

docs/milestones/cyan.md
=> ✨ Add article (#7118)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7125)

docs/milestones/blue.md
=> ✨ Add article (#7123)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7129)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7133)

docs/archived/broken_links.md, docs/changelog/2023_02.md, docs/milestones/brown.md
=> :boom: Move article to archives (#7137)

docs/blogs/algorithm/cpp.md
=> ✨ Add blog (#7032)

docs/blogs/heuristic/cpp.md, docs/blogs/heuristic/python.md
=> ✨ Add and update blogs (#6989)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7142)

docs/blogs/algorithm/cpp.md
=> :boom: Update domain (#7138)

docs/articles/view_scores.md
=> ✨ Add tweet (#7145)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7148)

docs/milestones/green.md
=> ✨ Add article (#7154)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7153)

docs/archived/broken_links.md, docs/related_contest_sites/algorithm.md
=> :boom: Move cotest site to archives (#7159)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7158)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7166)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7171)

docs/articles/development_env.md
=> ✨ Add video(#7167)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7174)

docs/related_contest_sites/joi_ioi.md
=> ✨ Add article (#7164)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7181)

docs/articles/algorithm.md
=> ✨ Add article (#7184)

.devcontainer/devcontainer.json
=> 🔧 Update settings and extensions for VS Code (#7197)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7193)

docs/milestones/cyan.md
=> ✨ Add article (#7200)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7201)

docs/blogs/heuristic/cpp.md, docs/blogs/heuristic/python.md
=> ✨ Add and update blogs (#7037)

docs/changelog/latest.md, docs/index.md
=> 🔊 Update CHANGELOG (#7203)
